### ISSUE TITLE
Can't Open the Menu (to disass. or decompile)

### ISSUE THREAD

**Issue by alefranzoni** [samczsun/Helios#42]
Hi, I'm using latest Helios and Java version "1.8.0_141" but when I wanna open a different view, I can't. On previous versions I did it by pressing right-clic, but now nothing happens.... Plus, I've read the README file and "To open a different view, simply use Ctrl-T" but, neither works for me.

Which could be the problem? Thanks

**Comment by samczsun** [comment]
What OS are you using?

**Comment by alefranzoni** [comment]
I'm using Windows 8.1

I only can open the menu over the complete file (to see 'Export' option, example over: test.jar) or over the HEX code (to see Save - Undo -  Copy - Paste) but over the classes/packages it's impossible, so weird.

Plus, I saw the menu just one time and I don't know how (I pressed a couple times Ctrl+T and Right-Click everywhere because It was driving me crazy and like magic, the menu was opened but nevermore)

**- - Edit - -**
Minutes ago the "Ctrl-T" was working perfect! But now, again don't work. Really it's so weird

**Comment by samczsun** [comment]
That's weird. Is your screen hdpi? Can you run Helios from the command line and see if any exceptions are thrown?

If you have the time, you can try debugging it in the IDE of your choosing. All the relevant code is [here](https://github.com/helios-decompiler/standalone-app/blob/master/src/main/java/com/heliosdecompiler/helios/gui/controller/AllFilesViewerController.java#L66). (Maybe there's some weird behaviour which is causing `isMenuOpen` to be inaccurate)

**Comment by alefranzoni** [comment]
Finally, I've catched the bug, bro. It's simple but I gonna try to be as clear as possible...

The bug occurs when you open a jar file and **BEFORE** to do double-click to any _***.class_** on it to open it (open the class selected in hex) you press "Ctrl-T" to open the menu. So then, the menu will not appear until re-open the program. Restart the workspace (Ctrl + N) don't fix the bug. Seems like pressing the shortcut before open a class is generating some error.

So:
- **[OK] >** Open file; Double click on a class (open it first) > Crtl + T > Menu work
- **[FAIL] >** Open file > Crtl + T > Menu don't work

I hope this info helps you!
Thanks for your time, work and support dude.

**Comment by samczsun** [comment]
Thanks! I'll take a look and see if I can reproduce it

**Comment by samczsun** [comment]
Huh. Funnily enough, I think this has already been fixed in the develop branch. Can you try [this](https://ci.samczsun.com/job/helios-decompiler/job/Standalone%20App/36/) build and see if you still encounter the problem?

**Comment by alefranzoni** [comment]
Great! I'm glad to say you that the **bug is fully fixed**. Now works like a charm! Thanks again for your support bro.
