### ISSUE TITLE
Killing a background task fails.

### ISSUE THREAD

**Issue by ghost** [samczsun/Helios#45]
I click the "X" button in the popup to kill the background task. The task doesnt die and neither does the dialog, but the "X" disappears. Thereafter the background task runs forever unless I restart Intellij. I find myself constantly having to restart intellij as a result.

Running version 2019.1.3 on Ubuntu 64bit

![image](https://user-images.githubusercontent.com/46291751/63639933-9069ed80-c6cc-11e9-8ab0-e6cf05f7c535.png)

**Comment by Janmm14** [comment]
Are you sure you created this issue in the right repository?

**Comment by ghost** [comment]
Sorry, my bad. Not sure how that ended here.
