### ISSUE TITLE
Why is a selected rt.jar location needed?

### ISSUE THREAD

**Issue by theuserbl** [samczsun/Helios#7]
Do I see it right, that Helios wants, that the user select the location of rt.jar? Why?

It is in
```
System.getProperty("java.home") + System.getProperty("file.separator") + "lib" + System.getProperty("file.separator") + "rt.jar"
```

**Comment by sh1ftchg** [comment]
This is one solution, but the jdk also has an rt.jar, and so does any other installed versions of Java. 

Also your solution works but it is wrong. Jars are selected from the properties "java.class.path" and "sun.boot.class.path".
